from __future__ import annotations

import re

from .models import TissueDefaults


def _tissue(
    name: str,
    simulation_mode: str,
    density_kg_m3: float,
    colour: tuple[float, float, float],
    opacity: float,
    youngs_modulus_pa: float | None = None,
    poissons_ratio: float | None = None,
    static_friction: float = 0.55,
    dynamic_friction: float = 0.35,
    damping_scale: float = 0.15,
    roughness: float = 0.58,
    semantic_class: str = "tissue",
    mesh_smoothing_mm: float = 0.8,
    mesh_smoothing_iterations: int = 4,
    mesh_closing_iterations: int = 1,
    mesh_keep_largest_component: bool = False,
    deformable_resolution: int = 14,
    texture_scale: tuple[float, float] = (3.0, 3.0),
    surface_detail: str = "organ",
    normal_strength: float = 0.28,
    detail_normal_strength: float = 0.1,
) -> TissueDefaults:
    return TissueDefaults(
        name=name,
        simulation_mode=simulation_mode,
        density_kg_m3=density_kg_m3,
        youngs_modulus_pa=youngs_modulus_pa,
        poissons_ratio=poissons_ratio,
        static_friction=static_friction,
        dynamic_friction=dynamic_friction,
        damping_scale=damping_scale,
        colour=colour,
        opacity=opacity,
        roughness=roughness,
        semantic_class=semantic_class,
        mesh_smoothing_mm=mesh_smoothing_mm,
        mesh_smoothing_iterations=mesh_smoothing_iterations,
        mesh_closing_iterations=mesh_closing_iterations,
        mesh_keep_largest_component=mesh_keep_largest_component,
        deformable_resolution=deformable_resolution,
        texture_scale=texture_scale,
        surface_detail=surface_detail,
        normal_strength=normal_strength,
        detail_normal_strength=detail_normal_strength,
    )


TISSUE_DEFAULTS: dict[str, TissueDefaults] = {
    "bone": _tissue(
        "bone",
        "rigid",
        1850.0,
        (0.86, 0.78, 0.62),
        1.0,
        youngs_modulus_pa=1.5e10,
        poissons_ratio=0.30,
        static_friction=0.8,
        dynamic_friction=0.55,
        roughness=0.68,
        semantic_class="bone",
        mesh_smoothing_mm=0.15,
        mesh_smoothing_iterations=1,
        mesh_closing_iterations=0,
        texture_scale=(7.0, 7.0),
        surface_detail="bone",
        normal_strength=0.42,
    ),
    "cancellous_bone": _tissue(
        "cancellous_bone",
        "rigid",
        1200.0,
        (0.78, 0.66, 0.50),
        1.0,
        youngs_modulus_pa=1.0e9,
        poissons_ratio=0.25,
        static_friction=0.75,
        dynamic_friction=0.5,
        roughness=0.72,
        semantic_class="bone",
        mesh_smoothing_mm=0.25,
        mesh_smoothing_iterations=1,
        mesh_closing_iterations=0,
        texture_scale=(8.0, 8.0),
        surface_detail="bone",
        normal_strength=0.48,
    ),
    "lung": _tissue(
        "lung",
        "deformable",
        350.0,
        (0.88, 0.42, 0.50),
        0.42,
        youngs_modulus_pa=5.0e3,
        poissons_ratio=0.47,
        damping_scale=0.35,
        roughness=0.82,
        semantic_class="lung",
        mesh_smoothing_mm=1.1,
        mesh_smoothing_iterations=5,
        deformable_resolution=8,
        texture_scale=(5.0, 5.0),
        surface_detail="lung",
        normal_strength=0.18,
    ),
    "liver": _tissue(
        "liver",
        "deformable",
        1060.0,
        (0.54, 0.12, 0.09),
        0.72,
        youngs_modulus_pa=1.2e4,
        poissons_ratio=0.48,
        damping_scale=0.28,
        roughness=0.44,
        semantic_class="organ",
        mesh_smoothing_mm=1.2,
        mesh_smoothing_iterations=6,
        mesh_keep_largest_component=True,
        deformable_resolution=10,
        texture_scale=(3.4, 3.4),
        surface_detail="organ",
        normal_strength=0.24,
    ),
    "kidney": _tissue(
        "kidney",
        "deformable",
        1050.0,
        (0.48, 0.08, 0.11),
        0.72,
        youngs_modulus_pa=1.0e4,
        poissons_ratio=0.48,
        damping_scale=0.28,
        roughness=0.46,
        semantic_class="organ",
        mesh_smoothing_mm=1.0,
        mesh_smoothing_iterations=5,
        mesh_keep_largest_component=True,
        deformable_resolution=10,
        texture_scale=(3.4, 3.4),
        surface_detail="organ",
        normal_strength=0.24,
    ),
    "spleen": _tissue(
        "spleen",
        "deformable",
        1060.0,
        (0.43, 0.08, 0.20),
        0.70,
        youngs_modulus_pa=8.0e3,
        poissons_ratio=0.48,
        damping_scale=0.3,
        roughness=0.45,
        semantic_class="organ",
        mesh_smoothing_mm=1.0,
        mesh_smoothing_iterations=5,
        mesh_keep_largest_component=True,
        deformable_resolution=10,
        texture_scale=(3.6, 3.6),
        surface_detail="organ",
        normal_strength=0.22,
    ),
    "heart": _tissue(
        "heart",
        "deformable",
        1060.0,
        (0.66, 0.10, 0.11),
        0.76,
        youngs_modulus_pa=5.0e4,
        poissons_ratio=0.47,
        damping_scale=0.22,
        roughness=0.38,
        semantic_class="organ",
        mesh_smoothing_mm=0.9,
        mesh_smoothing_iterations=4,
        mesh_keep_largest_component=True,
        deformable_resolution=12,
        texture_scale=(4.2, 4.2),
        surface_detail="heart",
        normal_strength=0.22,
    ),
    "muscle": _tissue(
        "muscle",
        "deformable",
        1070.0,
        (0.64, 0.20, 0.18),
        0.62,
        youngs_modulus_pa=6.0e4,
        poissons_ratio=0.46,
        damping_scale=0.2,
        roughness=0.58,
        semantic_class="muscle",
        mesh_smoothing_mm=0.7,
        mesh_smoothing_iterations=3,
        deformable_resolution=10,
        texture_scale=(6.0, 2.0),
        surface_detail="muscle",
        normal_strength=0.32,
    ),
    "fat": _tissue(
        "fat",
        "deformable",
        920.0,
        (0.94, 0.78, 0.42),
        0.58,
        youngs_modulus_pa=4.0e3,
        poissons_ratio=0.48,
        damping_scale=0.3,
        roughness=0.7,
        semantic_class="fat",
        mesh_smoothing_mm=1.0,
        mesh_smoothing_iterations=5,
        deformable_resolution=9,
        texture_scale=(4.0, 4.0),
        surface_detail="fat",
        normal_strength=0.16,
    ),
    "skin": _tissue(
        "skin",
        "deformable",
        1100.0,
        (0.78, 0.46, 0.36),
        0.44,
        youngs_modulus_pa=1.0e5,
        poissons_ratio=0.48,
        damping_scale=0.22,
        roughness=0.52,
        semantic_class="skin",
        mesh_smoothing_mm=1.6,
        mesh_smoothing_iterations=7,
        mesh_keep_largest_component=True,
        deformable_resolution=12,
        texture_scale=(5.5, 5.5),
        surface_detail="skin",
        normal_strength=0.18,
    ),
    "skin_shell": _tissue(
        "skin_shell",
        "surface_shell",
        1090.0,
        (0.78, 0.48, 0.38),
        0.30,
        youngs_modulus_pa=1.0e5,
        poissons_ratio=0.48,
        damping_scale=0.26,
        roughness=0.56,
        semantic_class="skin",
        mesh_smoothing_mm=2.0,
        mesh_smoothing_iterations=8,
        mesh_closing_iterations=2,
        mesh_keep_largest_component=True,
        deformable_resolution=0,
        texture_scale=(6.0, 6.0),
        surface_detail="skin",
        normal_strength=0.16,
    ),
    "blood": _tissue(
        "blood",
        "deformable",
        1060.0,
        (0.56, 0.02, 0.03),
        0.48,
        youngs_modulus_pa=1.0e3,
        poissons_ratio=0.49,
        damping_scale=0.45,
        roughness=0.2,
        semantic_class="fluid_like",
        mesh_smoothing_mm=0.6,
        mesh_smoothing_iterations=3,
        mesh_keep_largest_component=False,
        deformable_resolution=8,
        texture_scale=(2.2, 2.2),
        surface_detail="blood",
        normal_strength=0.1,
    ),
    "brain": _tissue(
        "brain",
        "deformable",
        1040.0,
        (0.82, 0.62, 0.54),
        0.62,
        youngs_modulus_pa=2.5e3,
        poissons_ratio=0.49,
        damping_scale=0.35,
        roughness=0.55,
        semantic_class="organ",
        mesh_smoothing_mm=1.1,
        mesh_smoothing_iterations=5,
        mesh_keep_largest_component=True,
        deformable_resolution=10,
        texture_scale=(3.8, 3.8),
        surface_detail="brain",
        normal_strength=0.18,
    ),
    "soft_tissue": _tissue(
        "soft_tissue",
        "deformable",
        1050.0,
        (0.74, 0.30, 0.28),
        0.58,
        youngs_modulus_pa=1.0e4,
        poissons_ratio=0.48,
        damping_scale=0.28,
        roughness=0.57,
        semantic_class="tissue",
        mesh_smoothing_mm=1.0,
        mesh_smoothing_iterations=5,
        deformable_resolution=10,
        texture_scale=(3.5, 3.5),
        surface_detail="soft_tissue",
        normal_strength=0.2,
    ),
}

_ALIASES: tuple[tuple[re.Pattern[str], str], ...] = (
    (re.compile(r"(skull|rib|vertebra|femur|humerus|clavicula|scapula|sacrum|hip|bone|mandible)"), "bone"),
    (re.compile(r"(trabecular|cancellous|spongiosa)"), "cancellous_bone"),
    (re.compile(r"lung"), "lung"),
    (re.compile(r"liver"), "liver"),
    (re.compile(r"kidney|renal"), "kidney"),
    (re.compile(r"spleen"), "spleen"),
    (re.compile(r"heart|myocard"), "heart"),
    (re.compile(r"muscle|psoas|gluteus"), "muscle"),
    (re.compile(r"fat|adipose|sat|subcutaneous"), "fat"),
    (re.compile(r"skin_shell|outer_skin|outer_shell|body_surface|body_envelope"), "skin_shell"),
    (re.compile(r"skin"), "skin"),
    (re.compile(r"blood|aorta|artery|vena|vein|vessel"), "blood"),
    (re.compile(r"brain|cerebr"), "brain"),
)


def normalise_label_name(label: str) -> str:
    label = label.strip().lower()
    label = re.sub(r"[^a-z0-9]+", "_", label)
    return label.strip("_")


def defaults_for_label(label: str) -> TissueDefaults:
    key = normalise_label_name(label)
    if key in TISSUE_DEFAULTS:
        return TISSUE_DEFAULTS[key]
    for pattern, target in _ALIASES:
        if pattern.search(key):
            return TISSUE_DEFAULTS[target]
    return TISSUE_DEFAULTS["soft_tissue"]


def is_rigid_label(label: str) -> bool:
    return defaults_for_label(label).simulation_mode == "rigid"
